server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://db:5432/chatdb}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

app:
  api-key: ${API_KEY:test_key}
  groq-api-url: https://api.groq.com/openai/v1/chat/completions
  groq-api-key: ${GROQ_API_KEY:dummy_key}


  rate:
    capacity: ${APP_RATE_CAPACITY:10}
    refill-tokens: ${APP_RATE_REFILL_TOKENS:10}
    refill-period-seconds: ${APP_RATE_REFILL_PERIOD_SECONDS:60}